DROP TABLE DIM_CHARGE_CATEG_SQL
DROP TABLE DIM_CUST_SQL
DROP TABLE dim_CUST_ACCT_SQL 
DROP TABLE dim_cust_address_SQL
DROP TABLE dim_cust_addr_zone_SQL
DROP TABLE dim_cust_addr1_sql
DROP TABLE DIM_CUST_CNTCT_SQL

DIM_CUST_EMAIL_SQL
DIM_CUST_PHONE_SQL
Dim_FULFMT_TYPE_LKP_SQL

Dim_OFFR_SQL
Dim_ORDER_STS_MASTER_LKP_SQL
DIM_ORG_BUSINESS_UNIT_SQL

Dim_ORG_TYPE_LKP_SQL
dim_prod_SQL
dim_rpt_hrchy_SQL
dim_RSN_LKP_sql
Dim_RSN_TYPE_LKP_sql
DIM_CUST_ACCT_DETAILS_SQL
